# Generated by Django 6.0.6 on 2026-06-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimizer', '0002_citycoordinate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['state'], name='route_optim_state_76d7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['city'], name='route_optim_city_2d1428_idx'),
        ),
    ]
